import 'package:freezed_annotation/freezed_annotation.dart';

@JsonEnum(alwaysCreate: true)
enum CarBrand {
  @JsonValue('Toyota')
  toyota,
  @JsonValue('Nissan')
  nissan,
  @JsonValue('Honda')
  honda,
  @JsonValue('Hyundai')
  hyundai,
  @JsonValue('Kia')
  kia,
  @JsonValue('BMW')
  bMW,
  @JsonValue('Mercedes')
  mercedes,
  @JsonValue('Audi')
  audi,
  @JsonValue('Volkswagen')
  volkswagen,
  @JsonValue('Ford')
  ford,
  @JsonValue('Chevrolet')
  chevrolet,
  @JsonValue('GMC')
  gMC,
  @JsonValue('Mitsubishi')
  mitsubishi,
  @JsonValue('Subaru')
  subaru,
  @JsonValue('Mazda')
  mazda,
  @JsonValue('Lexus')
  lexus,
  @JsonValue('Infiniti')
  infiniti,
  @JsonValue('Acura')
  acura,
  @JsonValue('LandRover')
  landRover,
  @JsonValue('Jaguar')
  jaguar,
  @JsonValue('Porsche')
  porsche,
  @JsonValue('Volvo')
  volvo,
  @JsonValue('Renault')
  renault,
  @JsonValue('Peugeot')
  peugeot,
  @JsonValue('Citroen')
  citroen,
  @JsonValue('Fiat')
  fiat,
  @JsonValue('Jeep')
  jeep,
  @JsonValue('Dodge')
  dodge,
  @JsonValue('Chrysler')
  chrysler,
  @JsonValue('Cadillac')
  cadillac,
  @JsonValue('Lincoln')
  lincoln,
  @JsonValue('Mini')
  mini,
  @JsonValue('Smart')
  smart,
  @JsonValue('Other')
  other,
}
