import 'package:freezed_annotation/freezed_annotation.dart';

@JsonEnum(alwaysCreate: true)
enum CarFeature {
  @JsonValue('ABS')
  aBS,
  @JsonValue('Airbags')
  airbags,
  @JsonValue('ParkingSensors')
  parkingSensors,
  @JsonValue('BackupCamera')
  backupCamera,
  @JsonValue('BlindSpotMonitor')
  blindSpotMonitor,
  @JsonValue('LaneDepartureWarning')
  laneDepartureWarning,
  @JsonValue('ForwardCollisionWarning')
  forwardCollisionWarning,
  @JsonValue('AdaptiveCruiseControl')
  adaptiveCruiseControl,
  @JsonValue('TractionControl')
  tractionControl,
  @JsonValue('StabilityControl')
  stabilityControl,
  @JsonValue('KeylessEntry')
  keylessEntry,
  @JsonValue('PushButtonStart')
  pushButtonStart,
  @JsonValue('HeatedSeats')
  heatedSeats,
  @JsonValue('CooledSeats')
  cooledSeats,
  @JsonValue('PowerSeats')
  powerSeats,
  @JsonValue('MemorySeats')
  memorySeats,
  @JsonValue('HeatedSteeringWheel')
  heatedSteeringWheel,
  @JsonValue('Sunroof')
  sunroof,
  @JsonValue('Moonroof')
  moonroof,
  @JsonValue('PanoramicRoof')
  panoramicRoof,
  @JsonValue('LeatherSeats')
  leatherSeats,
  @JsonValue('DualZoneClimateControl')
  dualZoneClimateControl,
  @JsonValue('RearACVents')
  rearACVents,
  @JsonValue('CruiseControl')
  cruiseControl,
  @JsonValue('Touchscreen')
  touchscreen,
  @JsonValue('Navigation')
  navigation,
  @JsonValue('Bluetooth')
  bluetooth,
  @JsonValue('AppleCarPlay')
  appleCarPlay,
  @JsonValue('AndroidAuto')
  androidAuto,
  @JsonValue('USBPorts')
  usbPorts,
  @JsonValue('WirelessCharging')
  wirelessCharging,
  @JsonValue('PremiumAudio')
  premiumAudio,
  @JsonValue('RearEntertainment')
  rearEntertainment,
  @JsonValue('AlloyWheels')
  alloyWheels,
  @JsonValue('LEDHeadlights')
  lEDHeadlights,
  @JsonValue('FogLights')
  fogLights,
  @JsonValue('RoofRails')
  roofRails,
  @JsonValue('Spoiler')
  spoiler,
  @JsonValue('TintedWindows')
  tintedWindows,
  @JsonValue('PowerMirrors')
  powerMirrors,
  @JsonValue('PowerTrunk')
  powerTrunk,
  @JsonValue('RemoteStart')
  remoteStart,
  @JsonValue('GarageDoorOpener')
  garageDoorOpener,
  @JsonValue('PaddleShifters')
  paddleShifters,
  @JsonValue('SportMode')
  sportMode,
  @JsonValue('EcoMode')
  ecoMode,
  @JsonValue('FourWheelDrive')
  fourWheelDrive,
  @JsonValue('DiffLock')
  diffLock,
}
