import 'package:freezed_annotation/freezed_annotation.dart';

@JsonEnum(alwaysCreate: true)
enum DogBreed {
  @JsonValue('Labrador')
  labrador,
  @JsonValue('GoldenRetriever')
  goldenRetriever,
  @JsonValue('GermanShepherd')
  germanShepherd,
  @JsonValue('Bulldog')
  bulldog,
  @JsonValue('Poodle')
  poodle,
  @JsonValue('Beagle')
  beagle,
  @JsonValue('Rottweiler')
  rottweiler,
  @JsonValue('Husky')
  husky,
  @JsonValue('ShihTzu')
  shihTzu,
  @JsonValue('Pomeranian')
  pomeranian,
  @JsonValue('Chihuahua')
  chihuahua,
  @JsonValue('Pitbull')
  pitbull,
  @JsonValue('Dalmatian')
  dalmatian,
  @JsonValue('Boxer')
  boxer,
  @JsonValue('CockerSpaniel')
  cockerSpaniel,
  @JsonValue('Maltese')
  maltese,
  @JsonValue('Pug')
  pug,
  @JsonValue('BorderCollie')
  borderCollie,
  @JsonValue('Doberman')
  doberman,
  @JsonValue('GreatDane')
  greatDane,
  @JsonValue('MixedBreed')
  mixedBreed,
  @JsonValue('Other')
  other,
}
