import 'package:freezed_annotation/freezed_annotation.dart';

@JsonEnum(alwaysCreate: true)
enum PhoneBrand {
  @JsonValue('Apple')
  apple,
  @JsonValue('Samsung')
  samsung,
  @JsonValue('Huawei')
  huawei,
  @JsonValue('Xiaomi')
  xiaomi,
  @JsonValue('OnePlus')
  onePlus,
  @JsonValue('Oppo')
  oppo,
  @JsonValue('Vivo')
  vivo,
  @JsonValue('Realme')
  realme,
  @JsonValue('Google')
  google,
  @JsonValue('Motorola')
  motorola,
  @JsonValue('Nokia')
  nokia,
  @JsonValue('Sony')
  sony,
  @JsonValue('LG')
  lG,
  @JsonValue('Asus')
  asus,
  @JsonValue('Lenovo')
  lenovo,
  @JsonValue('Honor')
  honor,
  @JsonValue('Infinix')
  infinix,
  @JsonValue('Tecno')
  tecno,
  @JsonValue('Alcatel')
  alcatel,
  @JsonValue('Blackberry')
  blackberry,
  @JsonValue('HTC')
  hTC,
  @JsonValue('Other')
  other,
}
