import 'package:freezed_annotation/freezed_annotation.dart';

@JsonEnum(alwaysCreate: true)
enum JobField {
  @JsonValue('Accounting')
  accounting,
  @JsonValue('Administration')
  administration,
  @JsonValue('Agriculture')
  agriculture,
  @JsonValue('Architecture')
  architecture,
  @JsonValue('Automotive')
  automotive,
  @JsonValue('Aviation')
  aviation,
  @JsonValue('Banking')
  banking,
  @JsonValue('Beauty')
  beauty,
  @JsonValue('BusinessDevelopment')
  businessDevelopment,
  @JsonValue('CallCenter')
  callCenter,
  @JsonValue('Construction')
  construction,
  @JsonValue('Consulting')
  consulting,
  @JsonValue('CustomerService')
  customerService,
  @JsonValue('Design')
  design,
  @JsonValue('Education')
  education,
  @JsonValue('Engineering')
  engineering,
  @JsonValue('Events')
  events,
  @JsonValue('Finance')
  finance,
  @JsonValue('Healthcare')
  healthcare,
  @JsonValue('Hospitality')
  hospitality,
  @JsonValue('HumanResources')
  humanResources,
  @JsonValue('InformationTechnology')
  informationTechnology,
  @JsonValue('Insurance')
  insurance,
  @JsonValue('InteriorDesign')
  interiorDesign,
  @JsonValue('Journalism')
  journalism,
  @JsonValue('Legal')
  legal,
  @JsonValue('Logistics')
  logistics,
  @JsonValue('Maintenance')
  maintenance,
  @JsonValue('Management')
  management,
  @JsonValue('Manufacturing')
  manufacturing,
  @JsonValue('Marketing')
  marketing,
  @JsonValue('Media')
  media,
  @JsonValue('NGO')
  ngO,
  @JsonValue('OilAndGas')
  oilAndGas,
  @JsonValue('Pharmaceutical')
  pharmaceutical,
  @JsonValue('Photography')
  photography,
  @JsonValue('PublicRelations')
  publicRelations,
  @JsonValue('Publishing')
  publishing,
  @JsonValue('QualityAssurance')
  qualityAssurance,
  @JsonValue('RealEstate')
  realEstate,
  @JsonValue('Research')
  research,
  @JsonValue('Restaurant')
  restaurant,
  @JsonValue('Retail')
  retail,
  @JsonValue('Sales')
  sales,
  @JsonValue('Security')
  security,
  @JsonValue('SocialServices')
  socialServices,
  @JsonValue('Sports')
  sports,
  @JsonValue('Telecommunications')
  telecommunications,
  @JsonValue('Tourism')
  tourism,
  @JsonValue('Training')
  training,
  @JsonValue('Translation')
  translation,
  @JsonValue('Transportation')
  transportation,
  @JsonValue('VideoGameDevelopment')
  videoGameDevelopment,
  @JsonValue('Warehousing')
  warehousing,
  @JsonValue('Wholesale')
  wholesale,
  @JsonValue('Other')
  other,
}
